---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 2
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box

suites:
- name: default
  run_list: ["recipe[dns::default]"]
  attributes:
    cloud:
      provider: vagrant
    dns:
      provider: aws
      credentials:
         aws_access_key_id: AWS_KEY
         aws_secret_access_key: AWS_PRIV
      entry:
        name: test1.test.rightscale.com
        type: A
        value: 192.168.1.1
